name: fcmcallerapp
description: FCM based caller application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^6.0.13

  #firebase_core: ^0.4.4+3
  #firebase_auth: ^0.15.5+3
  #firebase_analytics: ^5.0.11
  #firebase_crashlytics: ^0.1.3+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true




